<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit2444af01aa64c9f4f6226049a3b2b7e8
{
    public static $prefixLengthsPsr4 = array (
        'M' => 
        array (
            'Mike42\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Mike42\\' => 
        array (
            0 => __DIR__ . '/..' . '/mike42/escpos-php/src/Mike42',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit2444af01aa64c9f4f6226049a3b2b7e8::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit2444af01aa64c9f4f6226049a3b2b7e8::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit2444af01aa64c9f4f6226049a3b2b7e8::$classMap;

        }, null, ClassLoader::class);
    }
}
